spring:
  config:
    import: optional:file:.env[.properties]
  mvc:
    dispatch-options-request: true  
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: ${DB_DRIVER}
  jpa:
    hibernate:
      ddl-auto: ${DB_BEHAVIOR}
    show-sql: true
    properties:
      hibernate:
        dialect: ${DB_DIALECT}
        format_sql: true

jwt:
  secret: ${JWT_SECRET_KEY}

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui-custom.html

env-props:
    environment: K8S
    jwt-secret-key: ${JWT_SECRET_KEY}
    dev-url: ${DEV_URL:http://localhost:8081}
    prod-url: ${PROD_URL:https://rest.spot-me-app.com}
    origin: ${ORIGIN:http://localhost:8081}
    gateway-url: ${GATE_WAY_URL:http://localhost:8080}
    gateway-path: ${GATE_WAY_PATH:/auth}
    server-port: ${SERVER_PORT:8081}
    node-url: ${NODE_URL:http://${cluster}.magus.lab}

server:
  port: ${SERVER_PORT}

# Local